#ifndef EHCI_STORAGE_STATS_H
#define EHCI_STORAGE_STATS_H

#define EHCI_STORAGE_STATS_PARAMETER "EHCIStorageStats"
#define EHCI_STORAGE_PROFILE_PARAMETER "EHCIStorageProfile"
#define EHCI_IMOD_PARAMETER "EHCIInterruptModerationUS"
#define EHCI_STORAGE_STATS_VERSION 1
/* Ten 32-bit header words followed by low/high pairs of 64-bit metrics. */
#define EHCI_STORAGE_STATS_HEADER 10
enum {
    EHCI_STAT_READS, EHCI_STAT_BYTES, EHCI_STAT_ERRORS,
    EHCI_STAT_REQUEST_NS, EHCI_STAT_LOCK_NS, EHCI_STAT_MAP_NS,
    EHCI_STAT_CLIENT_COPY_NS, EHCI_STAT_UNMAP_NS,
    EHCI_STAT_STAGE_BASE
};
enum {
    EHCI_STAGE_COUNT, EHCI_STAGE_ERRORS, EHCI_STAGE_PREPARE_NS,
    EHCI_STAGE_SERVICE_NS, EHCI_STAGE_RESUME_NS, EHCI_STAGE_COPY_NS,
    EHCI_STAGE_TOTAL_NS, EHCI_STAGE_METRICS
};
enum { EHCI_STAGE_CBW, EHCI_STAGE_DATA, EHCI_STAGE_CSW, EHCI_STAGE_CONTROL,
       EHCI_STAGE_TYPES };
#define EHCI_STORAGE_METRICS (EHCI_STAT_STAGE_BASE + EHCI_STAGE_TYPES * EHCI_STAGE_METRICS)
#define EHCI_STORAGE_STATS_WORDS (EHCI_STORAGE_STATS_HEADER + 2 * EHCI_STORAGE_METRICS)

#endif
